services:
    best_it_contentful_translation.loader.contentful_loader:
        class: BestIt\ContentfulTranslationBundle\Loader\ContentfulLoader
        arguments:
            - '@best_it_contentful_translation.contentful_client'
            - '%best_it_contentful_translation.contentful_mapping%'
        tags:
            - { name: translation.loader, alias: contentful}